import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1>Hunting Coders</h1>
        </div>
        <p className={styles.description}>
          A blog for hunting coders from Arkham Asylum
        </p>
<div className={styles.imgcontainer}>
        <Image className={styles.img} alt="" src="/hacker.jpg" width={400} height={300} />
</div>

      <div className={styles.blogs}>
      <h2>Popular Blogs</h2>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
      </div>
      </main>
    </>
  )
}
